/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatesAddRequest
 */
export interface CoordinatesAddRequest {
    /**
     * 
     * @type {number}
     * @memberof CoordinatesAddRequest
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinatesAddRequest
     */
    y: number;
}

/**
 * Check if a given object implements the CoordinatesAddRequest interface.
 */
export function instanceOfCoordinatesAddRequest(value: object): value is CoordinatesAddRequest {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function CoordinatesAddRequestFromJSON(json: any): CoordinatesAddRequest {
    return CoordinatesAddRequestFromJSONTyped(json, false);
}

export function CoordinatesAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatesAddRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function CoordinatesAddRequestToJSON(json: any): CoordinatesAddRequest {
    return CoordinatesAddRequestToJSONTyped(json, false);
}

export function CoordinatesAddRequestToJSONTyped(value?: CoordinatesAddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

