/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatesResponse
 */
export interface CoordinatesResponse {
    /**
     * 
     * @type {number}
     * @memberof CoordinatesResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinatesResponse
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinatesResponse
     */
    y: number;
}

/**
 * Check if a given object implements the CoordinatesResponse interface.
 */
export function instanceOfCoordinatesResponse(value: object): value is CoordinatesResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function CoordinatesResponseFromJSON(json: any): CoordinatesResponse {
    return CoordinatesResponseFromJSONTyped(json, false);
}

export function CoordinatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'x': json['x'],
        'y': json['y'],
    };
}

export function CoordinatesResponseToJSON(json: any): CoordinatesResponse {
    return CoordinatesResponseToJSONTyped(json, false);
}

export function CoordinatesResponseToJSONTyped(value?: CoordinatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'x': value['x'],
        'y': value['y'],
    };
}

