/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatesUpdateRequest
 */
export interface CoordinatesUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof CoordinatesUpdateRequest
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinatesUpdateRequest
     */
    y?: number;
}

/**
 * Check if a given object implements the CoordinatesUpdateRequest interface.
 */
export function instanceOfCoordinatesUpdateRequest(value: object): value is CoordinatesUpdateRequest {
    return true;
}

export function CoordinatesUpdateRequestFromJSON(json: any): CoordinatesUpdateRequest {
    return CoordinatesUpdateRequestFromJSONTyped(json, false);
}

export function CoordinatesUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatesUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
    };
}

export function CoordinatesUpdateRequestToJSON(json: any): CoordinatesUpdateRequest {
    return CoordinatesUpdateRequestToJSONTyped(json, false);
}

export function CoordinatesUpdateRequestToJSONTyped(value?: CoordinatesUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

