/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FormOfEducation = {
    DistanceEducation: 'DISTANCE_EDUCATION',
    FullTimeEducation: 'FULL_TIME_EDUCATION',
    EveningClasses: 'EVENING_CLASSES'
} as const;
export type FormOfEducation = typeof FormOfEducation[keyof typeof FormOfEducation];


export function instanceOfFormOfEducation(value: any): boolean {
    for (const key in FormOfEducation) {
        if (Object.prototype.hasOwnProperty.call(FormOfEducation, key)) {
            if (FormOfEducation[key as keyof typeof FormOfEducation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FormOfEducationFromJSON(json: any): FormOfEducation {
    return FormOfEducationFromJSONTyped(json, false);
}

export function FormOfEducationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormOfEducation {
    return json as FormOfEducation;
}

export function FormOfEducationToJSON(value?: FormOfEducation | null): any {
    return value as any;
}

export function FormOfEducationToJSONTyped(value: any, ignoreDiscriminator: boolean): FormOfEducation {
    return value as FormOfEducation;
}

