/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonResponse } from './PersonResponse';
import {
    PersonResponseFromJSON,
    PersonResponseFromJSONTyped,
    PersonResponseToJSON,
    PersonResponseToJSONTyped,
} from './PersonResponse';

/**
 * 
 * @export
 * @interface PagedPersonResponse
 */
export interface PagedPersonResponse {
    /**
     * 
     * @type {Array<PersonResponse>}
     * @memberof PagedPersonResponse
     */
    content?: Array<PersonResponse>;
    /**
     * 
     * @type {number}
     * @memberof PagedPersonResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedPersonResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedPersonResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedPersonResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PagedPersonResponse interface.
 */
export function instanceOfPagedPersonResponse(value: object): value is PagedPersonResponse {
    return true;
}

export function PagedPersonResponseFromJSON(json: any): PagedPersonResponse {
    return PagedPersonResponseFromJSONTyped(json, false);
}

export function PagedPersonResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedPersonResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PersonResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PagedPersonResponseToJSON(json: any): PagedPersonResponse {
    return PagedPersonResponseToJSONTyped(json, false);
}

export function PagedPersonResponseToJSONTyped(value?: PagedPersonResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PersonResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

