/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinatesResponse } from './CoordinatesResponse';
import {
    CoordinatesResponseFromJSON,
    CoordinatesResponseFromJSONTyped,
    CoordinatesResponseToJSON,
    CoordinatesResponseToJSONTyped,
} from './CoordinatesResponse';

/**
 * 
 * @export
 * @interface PagedCoordinatesResponse
 */
export interface PagedCoordinatesResponse {
    /**
     * 
     * @type {Array<CoordinatesResponse>}
     * @memberof PagedCoordinatesResponse
     */
    content?: Array<CoordinatesResponse>;
    /**
     * 
     * @type {number}
     * @memberof PagedCoordinatesResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedCoordinatesResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedCoordinatesResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedCoordinatesResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PagedCoordinatesResponse interface.
 */
export function instanceOfPagedCoordinatesResponse(value: object): value is PagedCoordinatesResponse {
    return true;
}

export function PagedCoordinatesResponseFromJSON(json: any): PagedCoordinatesResponse {
    return PagedCoordinatesResponseFromJSONTyped(json, false);
}

export function PagedCoordinatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedCoordinatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(CoordinatesResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PagedCoordinatesResponseToJSON(json: any): PagedCoordinatesResponse {
    return PagedCoordinatesResponseToJSONTyped(json, false);
}

export function PagedCoordinatesResponseToJSONTyped(value?: PagedCoordinatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(CoordinatesResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

