/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudyGroupResponse } from './StudyGroupResponse';
import {
    StudyGroupResponseFromJSON,
    StudyGroupResponseFromJSONTyped,
    StudyGroupResponseToJSON,
    StudyGroupResponseToJSONTyped,
} from './StudyGroupResponse';

/**
 * 
 * @export
 * @interface PagedStudyGroupResponse
 */
export interface PagedStudyGroupResponse {
    /**
     * 
     * @type {Array<StudyGroupResponse>}
     * @memberof PagedStudyGroupResponse
     */
    content?: Array<StudyGroupResponse>;
    /**
     * 
     * @type {number}
     * @memberof PagedStudyGroupResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedStudyGroupResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedStudyGroupResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedStudyGroupResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PagedStudyGroupResponse interface.
 */
export function instanceOfPagedStudyGroupResponse(value: object): value is PagedStudyGroupResponse {
    return true;
}

export function PagedStudyGroupResponseFromJSON(json: any): PagedStudyGroupResponse {
    return PagedStudyGroupResponseFromJSONTyped(json, false);
}

export function PagedStudyGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedStudyGroupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(StudyGroupResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PagedStudyGroupResponseToJSON(json: any): PagedStudyGroupResponse {
    return PagedStudyGroupResponseToJSONTyped(json, false);
}

export function PagedStudyGroupResponseToJSONTyped(value?: PagedStudyGroupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(StudyGroupResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

