/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageModel
 */
export interface PageModel {
    /**
     * 
     * @type {Array<object>}
     * @memberof PageModel
     */
    content?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof PageModel
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PageModel
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageModel
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageModel
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageModel interface.
 */
export function instanceOfPageModel(value: object): value is PageModel {
    return true;
}

export function PageModelFromJSON(json: any): PageModel {
    return PageModelFromJSONTyped(json, false);
}

export function PageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageModel {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageModelToJSON(json: any): PageModel {
    return PageModelToJSONTyped(json, false);
}

export function PageModelToJSONTyped(value?: PageModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

