/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocationResponse } from './LocationResponse';
import {
    LocationResponseFromJSON,
    LocationResponseFromJSONTyped,
    LocationResponseToJSON,
    LocationResponseToJSONTyped,
} from './LocationResponse';

/**
 * 
 * @export
 * @interface PagedLocationResponse
 */
export interface PagedLocationResponse {
    /**
     * 
     * @type {Array<LocationResponse>}
     * @memberof PagedLocationResponse
     */
    content?: Array<LocationResponse>;
    /**
     * 
     * @type {number}
     * @memberof PagedLocationResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedLocationResponse
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedLocationResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedLocationResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PagedLocationResponse interface.
 */
export function instanceOfPagedLocationResponse(value: object): value is PagedLocationResponse {
    return true;
}

export function PagedLocationResponseFromJSON(json: any): PagedLocationResponse {
    return PagedLocationResponseFromJSONTyped(json, false);
}

export function PagedLocationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedLocationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(LocationResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PagedLocationResponseToJSON(json: any): PagedLocationResponse {
    return PagedLocationResponseToJSONTyped(json, false);
}

export function PagedLocationResponseToJSONTyped(value?: PagedLocationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(LocationResponseToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

