/* tslint:disable */
/* eslint-disable */
/**
 * IS Project API
 * Бэкенд для управления учебными группами и связанными сущностями. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Color } from './Color';
import {
    ColorFromJSON,
    ColorFromJSONTyped,
    ColorToJSON,
    ColorToJSONTyped,
} from './Color';
import type { Country } from './Country';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    CountryToJSONTyped,
} from './Country';
import type { LocationAddRequest } from './LocationAddRequest';
import {
    LocationAddRequestFromJSON,
    LocationAddRequestFromJSONTyped,
    LocationAddRequestToJSON,
    LocationAddRequestToJSONTyped,
} from './LocationAddRequest';

/**
 * 
 * @export
 * @interface PersonUpdateRequest
 */
export interface PersonUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof PersonUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {Color}
     * @memberof PersonUpdateRequest
     */
    eyeColor?: Color;
    /**
     * 
     * @type {Color}
     * @memberof PersonUpdateRequest
     */
    hairColor?: Color;
    /**
     * 
     * @type {number}
     * @memberof PersonUpdateRequest
     */
    locationId?: number;
    /**
     * 
     * @type {LocationAddRequest}
     * @memberof PersonUpdateRequest
     */
    location?: LocationAddRequest;
    /**
     * 
     * @type {boolean}
     * @memberof PersonUpdateRequest
     */
    removeLocation?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PersonUpdateRequest
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof PersonUpdateRequest
     */
    weight?: number;
    /**
     * 
     * @type {Country}
     * @memberof PersonUpdateRequest
     */
    nationality?: Country;
}



/**
 * Check if a given object implements the PersonUpdateRequest interface.
 */
export function instanceOfPersonUpdateRequest(value: object): value is PersonUpdateRequest {
    return true;
}

export function PersonUpdateRequestFromJSON(json: any): PersonUpdateRequest {
    return PersonUpdateRequestFromJSONTyped(json, false);
}

export function PersonUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'eyeColor': json['eyeColor'] == null ? undefined : ColorFromJSON(json['eyeColor']),
        'hairColor': json['hairColor'] == null ? undefined : ColorFromJSON(json['hairColor']),
        'locationId': json['locationId'] == null ? undefined : json['locationId'],
        'location': json['location'] == null ? undefined : LocationAddRequestFromJSON(json['location']),
        'removeLocation': json['removeLocation'] == null ? undefined : json['removeLocation'],
        'height': json['height'] == null ? undefined : json['height'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'nationality': json['nationality'] == null ? undefined : CountryFromJSON(json['nationality']),
    };
}

export function PersonUpdateRequestToJSON(json: any): PersonUpdateRequest {
    return PersonUpdateRequestToJSONTyped(json, false);
}

export function PersonUpdateRequestToJSONTyped(value?: PersonUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'eyeColor': ColorToJSON(value['eyeColor']),
        'hairColor': ColorToJSON(value['hairColor']),
        'locationId': value['locationId'],
        'location': LocationAddRequestToJSON(value['location']),
        'removeLocation': value['removeLocation'],
        'height': value['height'],
        'weight': value['weight'],
        'nationality': CountryToJSON(value['nationality']),
    };
}

