/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.chousik.is.api;

import ru.chousik.is.dto.request.LocationAddRequest;
import ru.chousik.is.dto.request.LocationUpdateRequest;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-10-12T18:03:55.081030+03:00[Europe/Moscow]", comments = "Generator version: 7.16.0")
@Validated
@Tag(name = "Locations", description = "the Locations API")
public interface LocationsApi {

    public static final String PATH_API_V1_LOCATIONS_BY_IDS_GET = "/api/v1/locations/by-ids";
    /**
     * GET /api/v1/locations/by-ids : Получить несколько локаций
     *
     * @param ids  (required)
     * @return Список локаций (status code 200)
     */
    @Operation(
        operationId = "apiV1LocationsByIdsGet",
        summary = "Получить несколько локаций",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список локаций", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ru.chousik.is.dto.response.LocationResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LocationsApi.PATH_API_V1_LOCATIONS_BY_IDS_GET,
        produces = { "application/json" }
    )
    
    ResponseEntity<List<ru.chousik.is.dto.response.LocationResponse>> apiV1LocationsByIdsGet(
        @NotNull @Parameter(name = "ids", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "ids", required = true) List<Long> ids
    );


    public static final String PATH_API_V1_LOCATIONS_DELETE = "/api/v1/locations";
    /**
     * DELETE /api/v1/locations : Массово удалить локации
     *
     * @param ids  (required)
     * @return Локации удалены (status code 204)
     */
    @Operation(
        operationId = "apiV1LocationsDelete",
        summary = "Массово удалить локации",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Локации удалены")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = LocationsApi.PATH_API_V1_LOCATIONS_DELETE
    )
    
    ResponseEntity<Void> apiV1LocationsDelete(
        @NotNull @Parameter(name = "ids", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "ids", required = true) List<Long> ids
    );


    public static final String PATH_API_V1_LOCATIONS_GET = "/api/v1/locations";
    /**
     * GET /api/v1/locations : Получить список локаций
     *
     * @param page Номер страницы (0-based) (optional)
     * @param size Размер страницы (optional)
     * @param sort Нативный параметр Spring для сортировки (optional)
     * @param sortBy Поле сортировки (optional)
     * @param direction Направление сортировки (optional)
     * @return Список локаций (status code 200)
     */
    @Operation(
        operationId = "apiV1LocationsGet",
        summary = "Получить список локаций",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список локаций", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = org.springframework.data.web.PagedModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LocationsApi.PATH_API_V1_LOCATIONS_GET,
        produces = { "application/json" }
    )
    
    ResponseEntity<org.springframework.data.web.PagedModel> apiV1LocationsGet(
        @Min(0) @Parameter(name = "page", description = "Номер страницы (0-based)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) @Nullable Integer page,
        @Min(1) @Parameter(name = "size", description = "Размер страницы", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false) @Nullable Integer size,
        @Parameter(name = "sort", description = "Нативный параметр Spring для сортировки", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false) @Nullable String sort,
        @Parameter(name = "sortBy", description = "Поле сортировки", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sortBy", required = false) @Nullable String sortBy,
        @Parameter(name = "direction", description = "Направление сортировки", in = ParameterIn.QUERY) @Valid @RequestParam(value = "direction", required = false) @Nullable String direction
    );


    public static final String PATH_API_V1_LOCATIONS_ID_DELETE = "/api/v1/locations/{id}";
    /**
     * DELETE /api/v1/locations/{id} : Удалить локацию
     *
     * @param id  (required)
     * @return Удалённая локация (status code 200)
     */
    @Operation(
        operationId = "apiV1LocationsIdDelete",
        summary = "Удалить локацию",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Удалённая локация", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ru.chousik.is.dto.response.LocationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = LocationsApi.PATH_API_V1_LOCATIONS_ID_DELETE,
        produces = { "application/json" }
    )
    
    ResponseEntity<ru.chousik.is.dto.response.LocationResponse> apiV1LocationsIdDelete(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    public static final String PATH_API_V1_LOCATIONS_ID_GET = "/api/v1/locations/{id}";
    /**
     * GET /api/v1/locations/{id} : Получить локацию по идентификатору
     *
     * @param id  (required)
     * @return Найденная локация (status code 200)
     */
    @Operation(
        operationId = "apiV1LocationsIdGet",
        summary = "Получить локацию по идентификатору",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Найденная локация", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ru.chousik.is.dto.response.LocationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LocationsApi.PATH_API_V1_LOCATIONS_ID_GET,
        produces = { "application/json" }
    )
    
    ResponseEntity<ru.chousik.is.dto.response.LocationResponse> apiV1LocationsIdGet(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    public static final String PATH_API_V1_LOCATIONS_ID_PATCH = "/api/v1/locations/{id}";
    /**
     * PATCH /api/v1/locations/{id} : Обновить локацию
     *
     * @param id  (required)
     * @param locationUpdateRequest  (required)
     * @return Обновлённая локация (status code 200)
     */
    @Operation(
        operationId = "apiV1LocationsIdPatch",
        summary = "Обновить локацию",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Обновлённая локация", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ru.chousik.is.dto.response.LocationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = LocationsApi.PATH_API_V1_LOCATIONS_ID_PATCH,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ru.chousik.is.dto.response.LocationResponse> apiV1LocationsIdPatch(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "LocationUpdateRequest", description = "", required = true) @Valid @RequestBody LocationUpdateRequest locationUpdateRequest
    );


    public static final String PATH_API_V1_LOCATIONS_PATCH = "/api/v1/locations";
    /**
     * PATCH /api/v1/locations : Массово обновить локации
     *
     * @param ids  (required)
     * @param locationUpdateRequest  (required)
     * @return Обновлённые локации (status code 200)
     */
    @Operation(
        operationId = "apiV1LocationsPatch",
        summary = "Массово обновить локации",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Обновлённые локации", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ru.chousik.is.dto.response.LocationResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = LocationsApi.PATH_API_V1_LOCATIONS_PATCH,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<List<ru.chousik.is.dto.response.LocationResponse>> apiV1LocationsPatch(
        @NotNull @Parameter(name = "ids", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "ids", required = true) List<Long> ids,
        @Parameter(name = "LocationUpdateRequest", description = "", required = true) @Valid @RequestBody LocationUpdateRequest locationUpdateRequest
    );


    public static final String PATH_API_V1_LOCATIONS_POST = "/api/v1/locations";
    /**
     * POST /api/v1/locations : Создать локацию
     *
     * @param locationAddRequest  (required)
     * @return Созданная локация (status code 200)
     */
    @Operation(
        operationId = "apiV1LocationsPost",
        summary = "Создать локацию",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Созданная локация", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ru.chousik.is.dto.response.LocationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = LocationsApi.PATH_API_V1_LOCATIONS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ru.chousik.is.dto.response.LocationResponse> apiV1LocationsPost(
        @Parameter(name = "LocationAddRequest", description = "", required = true) @Valid @RequestBody LocationAddRequest locationAddRequest
    );

}
