CREATE TABLE coordinates
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x  BIGINT                                  NOT NULL,
    y  FLOAT                                   NOT NULL,
    CONSTRAINT pk_coordinates PRIMARY KEY (id)
);

CREATE TABLE location
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x    INTEGER                                 NOT NULL,
    y    DOUBLE PRECISION                        NOT NULL,
    z    DOUBLE PRECISION                        NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE person
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    eye_color   VARCHAR(255),
    hair_color  VARCHAR(255)                            NOT NULL,
    location_id BIGINT,
    height      BIGINT                                  NOT NULL,
    weight      FLOAT                                   NOT NULL,
    nationality VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE study_group
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    coordinates_id       BIGINT                                  NOT NULL,
    creation_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    students_count       BIGINT,
    expelled_students    BIGINT                                  NOT NULL,
    transferred_students BIGINT                                  NOT NULL,
    form_of_education    VARCHAR(255),
    should_be_expelled   BIGINT                                  NOT NULL,
    average_mark         INTEGER,
    semester_enum        VARCHAR(255)                            NOT NULL,
    group_admin_id       BIGINT,
    CONSTRAINT pk_study_group PRIMARY KEY (id)
);

ALTER TABLE person
    ADD CONSTRAINT FK_PERSON_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);

ALTER TABLE study_group
    ADD CONSTRAINT FK_STUDY_GROUP_ON_COORDINATES FOREIGN KEY (coordinates_id) REFERENCES coordinates (id);

ALTER TABLE study_group
    ADD CONSTRAINT FK_STUDY_GROUP_ON_GROUPADMIN FOREIGN KEY (group_admin_id) REFERENCES person (id);